apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.0
  destination:
    server: https://kubernetes.default.svc
    namespace: dev 
  syncPolicy:
    automated:
      prune: true
    createNamespace: true
