apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-prod
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 18.1.14
      helm:
        valueFiles:
          - $values/apps/postgresql/values-prod.yaml
    - repoURL: https://github.com/parthokr/argocd-demo.git
      targetRevision: main
      ref: values
  
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
