apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  sources:
    # Source 1: The official Bitnami Helm Chart
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 18.1.14
      helm:
        valueFiles:
          - $values/apps/postgresql/values-dev.yaml
    - repoURL: https://github.com/your-username/my-gitops-repo.git
      targetRevision: main
      ref: values
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
