# argocd/vault.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.31.0
    helm:
      values: |
        server:
          dev:
            enabled: true
        postStart:
          - [/bin/sh, -c, |
              sleep 5;
              export VAULT_ADDR='http://127.0.0.1:8200';
              export VAULT_TOKEN='root';
              
              vault auth enable kubernetes || true;
              
              vault write auth/kubernetes/config \
                  kubernetes_host="https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT" || true;
            ]
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  destination:
    server: https://kubernetes.default.svc
    namespace: dev
